# services:
#   - type: web
#     name: isabi-fe
#     buildCommand: npm install && npm run build
#     staticPublishPath: dist  # Ensure this matches your Vite output directory

services:
  - type: web
    name: isabi-fe
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    plan: free
